language: python

dist: xenial

python: 3.6
python: 3.7
python: 3.8-dev
python: nightly

matrix:
  allow_failures:
    - python: 3.8-dev
    - python: nightly

install:
- pip install -e .

# script:
# - pytest

deploy:
  provider: pypi
  user: tylerwince
  password:
    secure: qlGs3YEcTxcST1RVaFU0MocJuRlOIzpbd4VsSmFO01zWzYQNgju3w9JfWMpVQ4chFA9z7HpRSovP9VVaDERvKTVdWhXYKhxlTHcpluxVU4Y/9g7NFmNmUsNKFZSTAmRUYZe2QZ4YWgTu/COy3INWwY2OmdJlukjtABw7wlI/koPd4AZuVJDxcv+V6lE1+ynCFB2N6oTG29kLzQinDP8MCKzjelsJrah9CTJG5LGL6ukEyOhIsUhm5OcT8nxLrhqiKyHAXWrHu2Es9C28MbW0y3o5GsPu4V1CJuAMcpO7UoqAcVY5PyjRI+kfRAQ1WN1h7LNE5L2TDU+VRqNyn97PzQ1HsiiV8HXo5zwi/uIoMdfmYwa6QP3UbHV8wjBvBxvvBld1xm6ewDukgtFgOHUxletEjgrvXtAf7xVBpu6xJHsUp+4OtvNKaOBYD0uhbbxSc0xHC9Gw3KKogEi6vo+cXkGdjsreFTWgmTXZyBz01X/miBGseTzqy1V+TqJTZCD2z0ZLnCNf8pweEDqTGLXgJfuS+ylrWxlqwKWIRq0cax5KwOeeMla1ffW2Ly1EriU6a3ECPsPLxt5NJNWkS/mle94eb/WGGN1/dilsIRNtTfu6liuQ1q4lkYC6AuA60Ia7OI4J739UxIAXT1lqA43NdNZD+Q6Nbh10oXII+3cqjXQ=
  on:
    branch: master
  skip_existing: true
